version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '00:00'
    assignees:
      - watcol
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '00:00'
    assignees:
      - watcol
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
