name: Release

on:
  push:
    branches:
      - release
  repository_dispatch:
    types: [contentful_update]

env:
  DEPLOY_ENV: RELEASE

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@master
        with:
          path: src
          ref: release

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true

      - name: Cache node_modules
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-v2

      - name: Install dependencies
        run: yarn
        working-directory: ./src

      - name: Generate sites
        env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ENVIRONMENT: master
          CONTENTFUL_DELIVERY_TOKEN: ${{ secrets.CONTENTFUL_DELIVERY_TOKEN }}
          CONTENTFUL_PREVIEW_TOKEN: ${{ secrets.CONTENTFUL_PREVIEW_TOKEN }}
        run: yarn build
        working-directory: ./src

      - name: Git and SSH configurations
        env:
          PUBLIC_DEPLOYKEY: ${{ secrets.PUBLIC_DEPLOYKEY }}
        run: |
          echo "$PUBLIC_DEPLOYKEY" > ~/deploykey.pem
          chmod 600 ~/deploykey.pem
          git config --global user.email "digital@nada-sc.jp"
          git config --global user.name "Github Actions"
      - name: Push pages
        env:
          GIT_SSH_COMMAND: ssh -i ~/deploykey.pem -o StrictHostKeyChecking=no -F /dev/
        run: |
          git clone git@github.com:NadaDigitalCommittee/FestPublic.git
          cd FestPublic
          # if [ -e ./2023/ ]; then
          #   rm -r ./2023/
          # fi
          mkdir ../old
          mv ./2022 ./_redirects ../old
          ls ./ | grep -v -E '^.git' | xargs rm -r
          mv ../src/build/ ./
          mv ../old/* ./
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Deploy NadaDigitalCommittee/Festival77@$GITHUB_SHA"
            git push origin main
          fi
